/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    403: (typeof import("./components/ErrorMessage/403.vue"))["default"];
    404: (typeof import("./components/ErrorMessage/404.vue"))["default"];
    500: (typeof import("./components/ErrorMessage/500.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
